---
- name: Converge
  hosts: all
  remote_user: centos
  become: true
  become_user: root
  vars_files:
    - ../../defaults/vault.yml
  vars:
    trend_slack_notify_enabled: false

  roles:
    - role: trend
