---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: centos-jenkins-ec2
    image: ami-07d45778
    instance_type: t2.micro
    vpc_subnet_id: subnet-b5af779e
    vpc_id: vpc-b6e29ed3
provisioner:
  name: ansible
  options:
    vvv: false
  config_options:
    defaults:
      vault_password_file: /etc/ansible/.vault/sc
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
